In [13]:
# riya Latkar
# 25070123092
# study of pandas

#convert data into table form

import pandas as pd

s= pd.Series([10,20,30,40])
display("table form of data is:",s)
print()


#Create Data Frame

data = {
    "Name":["A","B","C"],
    "Marks":[85,90,78]
}

df = pd.DataFrame(data)
display("the tabular form of data is:",df)
print()

#using head and tail command(which prints the first five columns[head] and last five columns[tail])

df.head
display("1st five columns are:",df.head())
print()

df.tail
display("last five columns are:",df.tail())
print()

#using shape in panda for telling no of rows and columns

df.shape
display("the shape of data is:",df.shape)
print()

#telling dimension of the table

df.ndim
display("the dimension of data is:",df.ndim)
print()

#telling total elements in table

df.size
display("the total elements in data is:",df.size)
print()

#displaying column names

df.columns
display("the column names are:",df.columns)
print()

#check data type of each column

df.dtypes
display("the data type of each column is:",df.dtypes)
print()

#accessing individual column

df["Name"]
display("the column name is:",df["Name"])
print()

df["Marks"]
display("the column name is:",df["Marks"])
print()

#display indivual row

df.loc[0]
display("the 1st row is:",df.loc[0])
print()

#for displaying indivisual element

df.iloc[1,1]
display("the element is:",df.iloc[1,1])
print()

#adding a new column

df["Grade"] = ["First class","Distinction","Second class"]
display("the new column is:",df)
print()

#change data in dataframe
#change marks in dataset
#using loc

df.loc[1,"Marks"] = 83
display("the new marks are:",df)
print()

#using iloc

df.iloc[0,1] = 87
display("the new marks are:",df)
print()

#delete a column same data frame(overwrite)

df.drop("Grade",axis=1,inplace=True) #axis determines row or column 0 determines row and  determines column and inplace means storing data in same place
print()

#delete a comlumn new dataframe

new_df = df.drop("Name",axis=1)
display("the new column is:",new_df)
print()

# perform basic statistical analysis
mean_marks = df["Marks"].mean()
print("The mean of marks is:", mean_marks)
print()


min_marks = min(df["Marks"])
print("the minimum marks is:",min_marks)
print()

max_marks = max(df["Marks"])
print("the maximum marks is:",max_marks)
print()

#Apply condition(filtering)
#display students scoing more marks than 80

filtered_df = df[df["Marks"]>80]
display("the students scoring more than 80 are:",filtered_df)

'table form of data is:'

0    10
1    20
2    30
3    40
dtype: int64

'the tabular form of data is:'

  Name  Marks
0    A     85
1    B     90
2    C     78

'1st five columns are:'

  Name  Marks
0    A     85
1    B     90
2    C     78

'last five columns are:'

  Name  Marks
0    A     85
1    B     90
2    C     78

'the shape of data is:'

(3, 2)

'the dimension of data is:'

2

'the total elements in data is:'

6

'the column names are:'

Index(['Name', 'Marks'], dtype='object')

'the data type of each column is:'

Name     object
Marks     int64
dtype: object

'the column name is:'

0    A
1    B
2    C
Name: Name, dtype: object

'the column name is:'

0    85
1    90
2    78
Name: Marks, dtype: int64

'the 1st row is:'

Name      A
Marks    85
Name: 0, dtype: object

'the element is:'

np.int64(90)

'the new column is:'

  Name  Marks         Grade
0    A     85   First class
1    B     90   Distinction
2    C     78  Second class

'the new marks are:'

  Name  Marks         Grade
0    A     85   First class
1    B     83   Distinction
2    C     78  Second class

'the new marks are:'

  Name  Marks         Grade
0    A     87   First class
1    B     83   Distinction
2    C     78  Second class

'the new column is:'

   Marks
0     87
1     83
2     78

The mean of marks is: 82.66666666666667

the minimum marks is: 78

the maximum marks is: 87

'the students scoring more than 80 are:'

  Name  Marks
0    A     87
1    B     83